### PR TITLE
Feature/hangouts

### PR DESCRIPTION
**Pull request by gauravtiwari**
Add a feature to support hangout link addition for a team member. At the moment, we usually share hangout links manually or start hangout using ```/hangout``` command from Slack, but it's inefficient as it involves extra steps *(inviting people, sharing links)* each time a hangout is created. @ohenrik had introduced something called permanent hangout - a hangout event that expires in far future, which we both tried out and worked great for us, but the problem was storing and retrieving this link efficiently. 
So, I have added this feature to spot hyper where a hangout link can be saved, updated and retrieved by typing these two commands right from your slack channel. You create and save url once and then just use the handy ```/myhangout``` command to retrieve either yours or a team members hangout url to join: 

### Usage
```bash
/myhangout [google_hangout_link]`  # To update or Add a new one
# Example: /myhangout http://bit.ly/1OZPgbY

/myhangout # To fetch the stored value

/hangoutwith [username]
# Example: /hangoutwith @gaurav
```

What you all think? rooms.hyper.no has introduced something similar, but it's limited to number of rooms. Keeping permanent hangouts will enable us to efficiently connect on hangout without hiccups - ```like "where is the link?", "I see a cat instead of you"?```

### CODE REVIEW

**Comment by RamonGilabert** [comment]
Can I merge this thing already! :yum:

**Comment by jgorset** [comment]
I just hate it when I think that I'm joining @ohenrik's Hangout and it turns out to be a cat's Hangout instead!

**Comment by jgorset** [comment]
I like this a lot, but should it really be on spot.hyper.no? It seems like it's own thing, or as you said, more related to @espenhogbakk rooms.hyper.no.

**Comment by gauravtiwari** [comment]
@jgorset Haha me too - So is this thing any good? I imagine this may increase communication, because we can ask everyone to have a permanent hangout and just bookmark it. There is also possibility to list it on SpotHyper so basically anyone can just get in touch with another. 
screen shot 2016-01-29 at 07 35 03

**Comment by gauravtiwari** [comment]
@jgorset Yeah I was about to make a separate app - but then I thought since, SpotHyper kind of deal with where a team member is and what he is working on, it would make sense to have a hangout link there?

**Comment by jgorset** [comment]
That's true; it makes sense in the context of that.

**Comment by jgorset** [comment]
We could even link the usernames of people in the list of spots.

**Comment by jgorset** [comment]
:sparkles: :cake: :sparkles:

**Comment by gauravtiwari** [comment]
@jgorset Yeah, I thought about ```user_name``` linking too within spots.

**Comment by gauravtiwari** [comment]
Awesome :+1: I will just double check this and see if we can get everyone to register a permanent hangout.

**Comment by gauravtiwari** [comment]
@RamonGilabert You likey :+1: it's merged

**Pull request merged**
